### ISSUE TITLE
Change JavaScript framework to JQuery

### ISSUE THREAD

**Issue by problem** [trails/trails#3]
"I’d suggest to change the way we work with javascript, perhaps another framework -maybe jquery- would support it" -- per this comment, I think we should definitely look into this. The app is very very slow right now ... I'm guessing it's because of this?

**Comment by kordero** [comment]
I don't think that we should continue in this way, I was wrong about this and not much familiar with this project client side code.

These days I think that we are doing very well with prototype.js, Also, If I recall good, I think that jquery had to do with somethign related to real REST support (through the 4 popupar HTTP methods), but considering that, because of a tiny patch we made on prototype, we are currently fully suporting REST, which improves compatibility with Rails routing turing the appa lot more simple, elegant and easier to debug. Let's have this issue closed for now.

**Comment by kordero** [comment]
About app being slow, is that still a current issue for you? I think that we made it way faster at a certain point when this comment was already posted.

**Comment by problem** [comment]
Awesome, sounds great.

How do you feel about prototype in general? It seems like the framework is fairly stagnant in terms of development. I know it was originally developed alongside Rails ... do you think the toolset it offers is suitable for at least another year or two based on our product goals?
